@startuml

== Чтение ==

Пользователь -> Сервер: Читаю все сообщения
Сервер -> BD: Читаю все сообщения
BD -> Сервер: Отправляю все сообщения
Пользователь <- Сервер: Отправляю все сообщения

== Сохранение ==

Пользователь -> Сервер: Отправляю сообщение
Сервер -> BD: Сохраняю сообщение

@enduml